language: node_js
node_js:
  - '0.10'

before_install:
  - 'npm install -g bower grunt-cli'

script:
  - 'npm install'
  - 'bower install'
  - 'gem install jekyll -v 2.5.3'
  - 'grunt build'
  - './node_modules/nsp/bin/nsp --shrinkwrap npm-shrinkwrap.json check --output summary'
  - 'npm test'

after_success:
  - sh -x ./scripts/publish.sh
